$(document).ready(function(){jQuery('#HTML399').appendTo(jQuery('.post-body p')[2]);}); 
$(document).ready(function(){jQuery('#MBL-Ads').appendTo(jQuery('a[name="more"]'));}); 
$(document).ready(function(){jQuery('#HTML339').appendTo(jQuery('.post-body LessonNote'));}); 
$(document).ready(function(){jQuery('#HTML335').appendTo(jQuery('.post-body MoreLink'));}); 
$(document).ready(function(){jQuery('#HTML348').appendTo(jQuery('.post-body eBook'));}); 
$(document).ready(function(){jQuery('#HTML357').appendTo(jQuery('.post-body Note'));}); 
$(document).ready(function(){jQuery('#HTML366').appendTo(jQuery('.post-body Collection'));}); 
$(document).ready(function(){jQuery('#HTML377').appendTo(jQuery('.post-body PolyQCM'));}); 
$(document).ready(function(){jQuery('#HTML388').appendTo(jQuery('.post-body Regarde'));}); 
$(document).ready(function(){jQuery('#HTML355').appendTo(jQuery('.post-body Apps'));});
